export const baseOnboarding = {
  firstName: "Jane",
  lastName: "Smith",
  email: "jane@example.com",
  companyName: "Smith Plumbing",
  businessRole: "Owner",
  website: "https://smithplumbing.example",
  businessDescription: "Residential plumbing repair and installation.",
  growthFocus: "Water heater installs",
  growthAreas: "Scottsdale, Tempe",
  primaryOutcome: "More qualified calls",
  success90: "More calls",
  highValueWork: "Water heater replacement",
  primaryConversion: "Phone call",
  responseOwner: "Office manager",
  callTracking: "No",
  outcomesTracking: "We track outcomes manually",
  reportRecipients: "Jane Smith, jane@example.com, Owner",
  communicationPreference: "Email",
};
