export const baseOnboarding = {
  firstName: "Jane",
  lastName: "Smith",
  email: "jane@example.com",
  companyName: "Smith Plumbing",
  businessRole: "Owner",
  businessCity: "Tempe",
  businessState: "AZ",
  websiteStatus: "yes",
  website: "https://smithplumbing.example",
  businessDescription: "Residential plumbing repair and installation.",
  growthFocus: "Water heater installs",
  growthAreas: "Scottsdale, Tempe",
  preferredContact: "Phone calls",
  holdingBack: "Not enough reviews",
  differentiator: "Same-day service",
  exclusions: "None",
  success90: "More calls",
  successYear: "Steady bookings",
  highValueWork: "Water heater replacement",
  competitors: "Not sure",
  optionalKeywords: "plumber near me",
  responseOwner: "Office manager",
  callTracking: "No",
  outcomesTracking: "We track it by hand (spreadsheet, notebook)",
  formDestination: "Email inbox",
  leadChallenges: "None",
  reportRecipients: "Jane Smith, jane@example.com, Owner",
  communicationPreference: "Email",
};
